source/hello/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.views.generic import RedirectView

from webapp.views import IndexView, CreateArticle, ArticleView, UpdateArticle, DeleteArticle, CreateCommentView, \
    UpdateComment, DeleteComment

from webapp.views.likes import ArticleLikes, CommentLikes

app_name = "webapp"

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('articles/', RedirectView.as_view(pattern_name="index")),
    path('articles/add/', CreateArticle.as_view(), name="create_article"),
    path('article/<int:pk>/', ArticleView.as_view(), name="article_view"),
    path('article/<int:pk>/update/', UpdateArticle.as_view(), name="update_article"),
    path('article/<int:pk>/delete/', DeleteArticle.as_view(), name="delete_article"),
    path('article/<int:pk>/comment/add/', CreateCommentView.as_view(), name="article_comment_create"),
    path('comments/<int:pk>/update/', UpdateComment.as_view(), name="update_comment"),
    path('comments/<int:pk>/delete/', DeleteComment.as_view(), name="delete_comment"),
    path('like/<int:pk>/', ArticleLikes.as_view(), name='like_article'),
    path('like_com/<int:pk>/', CommentLikes.as_view(), name='like_comment'),

]

source/webapp/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
from django.urls import reverse

from .validate import validate_title

# from source.accounts.views import User


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")

    class Meta:
        abstract = True


class Article(BaseModel):
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name="Заголовок")
    content = models.TextField(max_length=3000, verbose_name="Контент")
    tags = models.ManyToManyField("webapp.Tag", related_name="articles", blank=True)
    author = models.ForeignKey(get_user_model(), related_name="articles", verbose_name="Автор", default=1,
                               on_delete=models.SET_DEFAULT)
    likes = models.ManyToManyField(get_user_model(), verbose_name='Лайки')

    def __str__(self):
        return f"{self.id}. {self.title}: {self.author.username}"

    def get_absolute_url(self):
        return reverse("webapp:article_view", kwargs={"pk": self.pk})

    def upper(self):
        return self.title.upper()

    class Meta:
        db_table = "articles"
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        # permissions = [
        #     ('сan_have_piece_of_pizza', 'Может съесть кусочек пиццы')
        # ]


class Comment(BaseModel):
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    author = models.ForeignKey(get_user_model(), related_name="comments", verbose_name="Автор", default=1,
                               on_delete=models.SET_DEFAULT)
    article = models.ForeignKey("webapp.Article", on_delete=models.CASCADE, related_name="comments", verbose_name="Статья")
    likes = models.ManyToManyField(get_user_model(), verbose_name='Лайки')

    def __str__(self):
        return f"{self.id}. {self.text}: {self.author.username}"

    class Meta:
        db_table = "comments"
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


class Tag(BaseModel):
    name = models.CharField(max_length=31, verbose_name='Тег')

    def __str__(self):
        return self.name

    class Meta:
        db_table = "tags"
        verbose_name = "Тэг"
        verbose_name_plural = "Тэги"

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets
from webapp.models import Article, Comment


class UserArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title"]


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "tags"]
        widgets = {
            "tags": widgets.CheckboxSelectMultiple,
            "content": widgets.Textarea(attrs={"placeholder": "введите контент"})
        }

    def clean(self):
        if self.cleaned_data.get("title") == self.cleaned_data.get("content"):
            raise ValidationError("Название и описание не могут совпадать")
        return super().clean()


class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Найти')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]


class ArticleDeleteForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title"]

    def clean_title(self):
        title = self.cleaned_data.get("title")
        if self.instance.title != title:
            raise ValidationError("Названия не совпадают")
        return title

source/webapp/views/articles.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.db.models import Q
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy

# Create your views here.
from django.utils.http import urlencode

from webapp.forms import ArticleForm, SearchForm, ArticleDeleteForm, UserArticleForm
from webapp.models import Article
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


class IndexView(ListView):
    model = Article
    template_name = "articles/index.html"
    context_object_name = "articles"
    ordering = "-updated_at"
    paginate_by = 6

    def get(self, request, *args, **kwargs):
        # print(request.user.user_permissions.all())
        # request.user.user_permissions.add(Permission.objects.get(codename="delete_article"))
        # print(request.user.user_permissions.all())
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)
        # return JsonResponse({'test': 1, 'test2': [1, 2, 3]})

    def get_queryset(self):
        if self.search_value:
            return Article.objects.filter(
                Q(author__icontains=self.search_value) |
                Q(title__icontains=self.search_value)).order_by("-updated_at")
        return Article.objects.all().order_by("-updated_at")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        if self.search_value:
            query = urlencode({'search': self.search_value})  # search=dcsdvsdvsd
            context['query'] = query
            context['search'] = self.search_value
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get("search")


class ArticleView(DetailView):
    template_name = "articles/article_view.html"
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.order_by("-created_at")
        return context


class CreateArticle(LoginRequiredMixin, CreateView):
    form_class = ArticleForm
    template_name = "articles/create.html"

    # def dispatch(self, request, *args, **kwargs):
    #     if request.user.is_authenticated and self.request.user.has_perm("webapp.add_article"):
    #         return super().dispatch(request, *args, **kwargs)
    #     return redirect("accounts:login")

    def form_valid(self, form):
        user = self.request.user
        form.instance.author = user
        return super().form_valid(form)


class UpdateArticle(PermissionRequiredMixin, UpdateView):
    form_class = ArticleForm
    template_name = "articles/update.html"
    model = Article

    def has_permission(self):
        return self.request.user.has_perm("webapp.change_article") or \
               self.request.user == self.get_object().author


class DeleteArticle(PermissionRequiredMixin, DeleteView):
    model = Article
    template_name = "articles/delete.html"
    success_url = reverse_lazy('webapp:index')
    form_class = ArticleDeleteForm
    permission_required = "webapp.delete_article"

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

        # return self.request.user.is_superuser or \
        #        self.request.user.groups.filter(name__in=("Модераторы",)).exists()

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST, instance=self.get_object())
        if form.is_valid():
            return self.delete(request, *args, **kwargs)
        else:
            return self.get(request, *args, **kwargs)

source/webapp/views/base_view.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from django.views.generic import TemplateView


class DeleteView(View):
    template_name = None
    confirm_deletion = True
    model = None
    key_kwarg = 'pk'
    context_key = 'object'
    redirect_url = ''

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.confirm_deletion:
            return render(request, self.template_name, self.get_context_data())
        else:
            self.perform_delete()
            return redirect(self.get_redirect_url())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.perform_delete()
        return redirect(self.get_redirect_url())

    def perform_delete(self):
        self.object.delete()

    def get_context_data(self, **kwargs):
        return {self.context_key: self.object}

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_redirect_url(self):
        return self.redirect_url

class UpdateView(View):
   form_class = None
   template_name = None
   redirect_url = ''
   model = None
   key_kwarg = 'pk'
   context_key = 'object'

   def get(self, request, *args, **kwargs):
       self.object = self.get_object()
       form = self.form_class(instance=self.object)
       context = self.get_context_data(form=form)
       return render(request, self.template_name, context=context)

   def post(self, request, *args, **kwargs):
       self.object = self.get_object()
       form = self.form_class(instance=self.object, data=request.POST)
       if form.is_valid():
           return self.form_valid(form)
       else:
           return self.form_invalid(form)

   def form_valid(self, form):
       self.object = form.save()
       return redirect(self.get_redirect_url())

   def form_invalid(self, form):
       context = self.get_context_data(form=form)
       return render(self.request, self.template_name, context=context)

   def get_object(self):
       pk = self.kwargs.get(self.key_kwarg)
       return get_object_or_404(self.model, pk=pk)

   def get_context_data(self, **my_kwargs):
       context = self.kwargs.copy()
       context[self.context_key] = self.object
       context.update(my_kwargs)
       return context

   def get_redirect_url(self):
       return self.redirect_url


class CreateView(View):
    form_class = None
    template_name = None
    model = None
    redirect_url = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = {'form': form}
        return render(self.request, self.template_name, context)

    def get_redirect_url(self):
        return self.redirect_url

class DetailView(TemplateView):
    context_key = 'object'
    model = None
    key_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_object()
        return context

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)


class ListView(TemplateView):
    model = None
    context_key = "objects"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_objects()
        return context

    def get_objects(self):
        return self.model.objects.all()


class FormView(View):
    form_class = None
    template_name = None
    redirect_url = ""

    def get_redirect_url(self):
        return redirect(self.redirect_url)

    def get(self, request):
        form = self.form_class()
        context = self.get_context(form=form)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        return self.form_isvalid(form)

    def get_context(self, **kwargs):
        return kwargs

    def form_valid(self, form):
        return self.get_redirect_url()

    def form_isvalid(self, form):
        context = self.get_context(form=form)
        return render(self.request, self.template_name, context)

source/webapp/views/comments.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import CommentForm
from webapp.models import Article, Comment


class CreateCommentView(CreateView):
    form_class = CommentForm
    template_name = "comments/create.html"

    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs.get("pk"))
        user = self.request.user
        form.instance.article = article
        form.instance.author = user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:article_view", kwargs={"pk": self.object.article.pk})


class UpdateComment(UserPassesTestMixin, UpdateView):
    form_class = CommentForm
    template_name = "comments/update.html"
    model = Comment

    def test_func(self):
        return self.get_object().author == self.request.user or\
               self.request.user.has_perm('webapp.change_comment')

    def get_success_url(self):
        return reverse("webapp:article_view", kwargs={"pk": self.object.article.pk})


class DeleteComment(DeleteView):
    model = Comment

    def get(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("webapp:article_view", kwargs={"pk": self.object.article.pk})

source/webapp/views/likes.py
from django.http import JsonResponse
from django.views.generic.base import View

from webapp.models import Article, Comment


class ArticleLikes(View):
    def get(self, request, *args, **kwargs):
        article = Article.objects.get(pk=kwargs.get('pk'))
        user = self.request.user
        if user not in article.likes.all():
            article.likes.add(user)
            return JsonResponse({'likes': article.likes.all().count(), 'pk': article.pk})
        article.likes.remove(user)
        return JsonResponse({'likes': article.likes.all().count(), 'pk': article.pk})


class CommentLikes(View):
    def get(self, request, *args, **kwargs):
        comment = Comment.objects.get(pk=kwargs.get('pk'))
        user = request.user
        if user not in comment.likes.all():
            comment.likes.add(user)
            return JsonResponse({'likes': comment.likes.all().count(), 'pk': comment.pk})
        comment.likes.remove(user)
        return JsonResponse({'likes': comment.likes.all().count(), 'pk': comment.pk})

source/webapp/templates/articles/article_view.html
{% extends "base.html" %}
{% block nav %}
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:create_article" %}">Создание статьи</a>
        </li>
        {% if perms.webapp.change_article or user == article.author %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "webapp:update_article" article.pk %}">Редактировать</a>
            </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:article_comment_create" article.pk %}">Добавить коммент</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:delete_article" article.pk %}">Удалить</a>
        </li>

    {% endif %}
{% endblock %}

{% block content %}
    <div class="card mt-3">
        <div class="card-body text-center">
            <h5 class="card-title">{{ article.upper }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Автор: {{ article.author }}</h6>
            <p class="card-text">{{ article.content }}</p>
            <button class="btn btn-info" id="button"  data-articles-link="{% url "webapp:like_article" article.pk %}">Likes</button>
        </div>
    </div>
    <h3 class="my-3 text-center">Комментарии</h3>
    <div class="row">
        {% for comment in comments %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <p class="card-text">{{ comment.text }}</p>
                    </div>
                    <div class="btn-group w-100" role="group" aria-label="Basic mixed styles example">
                        <a class="btn btn-danger" href="{% url "webapp:update_comment" comment.pk %}">Изменить</a>
                        <a class="btn btn-warning" href="{% url "webapp:delete_comment" comment.pk %}">Удалить</a>
                       <button  class="btn btn-info" id="button_c" data-comments-link="{% url "webapp:like_comment" comment.pk %}">Likes</button>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>Комментариев нет</p>
        {% endfor %}
    </div>
    <h3>Теги</h3>
    {% for tag in article.tags.all %}
        <p>{{ tag.name }}</p>
        {% empty %}
        <p>Тэгов нет</p>
    {% endfor %}
    <a href="{% url "webapp:index" %}">На главную</a>

    <div class="modal fade" id="articleDeleteModal" tabindex="-1" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="articleDeleteModal">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Вы уверены что хотите удалить статью {{ article.title }}?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{% url "webapp:update_article" article.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Да</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

source/webapp/templates/articles/create.html
{% extends "base.html" %}
{% block title %}Создание статьи{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Создание статьи</h1>
        <form action="" method="post">
            {% include "partial/form.html" with button_text="Создать" %}
        </form>
        <a href="{% url "webapp:index" %}">На главную</a>
    </div>
{% endblock %}

source/webapp/templates/articles/delete.html
{% extends "base.html" %}
{% block title %}Удаление статьи{% endblock %}

{% block content %}
    <h2>Введите название статьи ({{ article.title }}) для удаления</h2>
    <form action="" method="post">
        {% csrf_token %}
        {% include "partial/form.html" with button_text="Удалить" %}
    </form>
    <a href="{% url "webapp:article_view" article.pk %}">Назад</a>
{% endblock %}

source/webapp/templates/articles/index.html
{% extends "base.html" %}
{% load static %}
{% block nav %}

    {% if perms.webapp.add_article %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:create_article" %}">Создание статьи</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="mt-3">
        {% include "partial/search.html" %}
    </div>

    {% include "partial/articles_list_partial.html" %}
{% endblock %}

source/webapp/templates/articles/update.html
{% extends "base.html" %}
{% block title %}Изменение статьи{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Изменение статьи</h1>
        <form action="" method="post">
            {% include "partial/form.html" with button_text="Изменить" %}
        </form>
        <a href="{% url "webapp:index" %}">На главную</a>
    </div>
{% endblock %}